### ISSUE TITLE
Why is dogescript ded?

### ISSUE THREAD

**Issue by lordjbs** [dogescript/dogescript#101]
;-;

**Comment by Extarys** [comment]
:( sad looked much funny

**Comment by vpzomtrrfrt** [comment]
In case anyone cares, I set up http://dogescript.science

**Comment by AnEmortalKid** [comment]
@vpzomtrrfrt  how did you get dogescript to be required?

I've tried using `var dogescript = require('dogescript');` and then `browserify index.js -o bundle.js` but it doesn't seem that dogescript is loaded. For reference:
```
var dogescript = require('dogescript');
var $ = require('jquery');

console.log('loaded');
```

Will have `$` loaded but not `dogescript`

**Comment by vpzomtrrfrt** [comment]
All I did here was rehost the old site. I don't really know anything about browserify

**Comment by AnEmortalKid** [comment]
@vpzomtrrfrt so, I descended into the madness and made a few samples of different ways to get dogescript running:

http://anemortalkid.github.io/dogetest/

This guy: http://anemortalkid.github.io/dogetest/rundogescript/

Should have a button that lets you execute. Mayhaps you'd like to edit http://dogescript.science/live/ to have a button like that, I could probably help out.

**Comment by AnEmortalKid** [comment]
still dead? maybe @Pholey  has the power to give one of us access to merge things

**Comment by AnEmortalKid** [comment]
closing since the second wind has come.
