### ISSUE TITLE
Such revive 2.4 and 3.x

### ISSUE THREAD

**Issue by AnEmortalKid** [dogescript/dogescript#105]
Howdy! 

So I've been digging around and in this issue: https://github.com/dogescript/dogescript/issues/96 @idunnowhy9000 used PegJs to rewrite dogescript, found here: https://github.com/idunnowhy9000/dogescript

After dealing with the crazy parser, I had also considered using PegJs. 

I'm thinking we could freeze the state of dogescript with what It has right now (release 2.4) and then port over to pegjs. Since it would be a 3.0, I've been thinking we make some breaking changes:

assignment: keep `is` and `as`. 
operators: change `is` to `same`
Loops: change for loop from `much` to `lots`

Functions: 

Keep `such [name] much [vars]` 
Support anonymous functions with just `much [vars]`. This would be feasible since the for loop name doesn't conflict. 

We can bring in the elements from dogescript-3 like `dogeof`

Add a different operator for `})` instead of `wow&`. Maybe amaze or excite. 

Arrays: 
Maybe add a `gimme` that replaces `array[0]` so `array gimme 0` and for multiple dimensions `array gimme 0 gimme 1`

Thoughts/opinions?

**Comment by AnEmortalKid** [comment]
@Pholey thoughts?

**Comment by remixz** [comment]
@AnEmortalKid Sorry I've been unresponsive! I've added you to @dogescript/core, so you should be able to merge PRs and such. 

As a sort of statement: I'm not really planning to be involved with the development of Dogescript going forward (aside from watching and enjoying what everyone comes up with 😄 ), so I'm open and 👍  to whatever the rest of @dogescript/core and the community wants to do. My only request is that everyone is kind and respectful to each other. Adding a Code of Conduct (https://github.com/dogescript/dogescript/community/code-of-conduct/new) would be an idea I'm in favour of. 

Please do ping me again if something comes up I can help with, and I'll try to respond a bit faster. 😅

**Comment by AnEmortalKid** [comment]
More suggestions found here: #35 

Digging: `also`, `totally`, `noway`, the `bones` and `also` for comma is also neat.

**Comment by AnEmortalKid** [comment]
Cross referencing: https://github.com/idunnowhy9000/dogescript/blob/master/LANGUAGE.md . I like the way that markdown was organized as well.

**Comment by Pholey** [comment]
I believe one of the goals of dogescript 3.0 was to write a [dogescript parser in dogescript](https://github.com/dogescript/dogescript/issues/96), and figure out what exactly we need to make that happen and throw that into 2.4 (2.5?). I think writing it in pegjs might bring in a lot of complexity for contributors, and take away from the magic of a self-hosted interpreter

**Comment by Pholey** [comment]
I believe one of the goals of dogescript 3.0 was to write a [dogescript parser in dogescript](https://github.com/dogescript/dogescript/issues/96), and figure out what exactly we need to make that happen and throw that into 2.4 (2.5?). I think writing it in pegjs might bring in a lot of complexity for contributors, and take away from the magic of a self-hosted interpreter

**Comment by AnEmortalKid** [comment]
"The goal is currently for 3.0 is to rewrite the current dogescript compiler in ES6, then port that over to dogescript afterwards (ending in full ES6 support hopefully!)"

I've never written a parser / lexer before, so that could be fun to try out. I guess I'll read about them. I do like the look ahead or greedy aspect of it, ideally our parser/lexer would also let us do `plz doge with plz cat` and would fix the white space problem. We can still introduce `also` to separate arguments passed in and use it like a ,

**Comment by Pholey** [comment]
They really aren't all too bad, ideally while it can just be a fair amount of work, it is just code at the end of the day! Hopefully should have a working tokenizer this weekend or the next :) Closing this ticket as i would like to consolidate all of the 2.4/3.0 feature requests and link to them in new tickets. Hopefully will get some time to do some stale issue clean up later tonight
