### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by AnEmortalKid** [dogescript/dogescript#116]
add contributing.md so our community health is better. #117

**Comment by williamsthing** [comment]
![this is what a fucking meme language has done to my inbox. thanks guys.](https://user-images.githubusercontent.com/8293444/31461007-0bb1398e-aec0-11e7-9606-23c8d30584d0.PNG)

**Comment by AnEmortalKid** [comment]
how did you get all those?

**Comment by AnEmortalKid** [comment]
@williamsthing is it cause you have this repository star'ed? oh lord i hope we haven't been spamming everyone.

**Comment by Griffork** [comment]
You have.

**Comment by AnEmortalKid** [comment]
sorry :( hopefully you guys could tell that pholey and i were busy!

**Comment by Griffork** [comment]
Yep. We can always unstar if it's a problem.

**Comment by vpzomtrrfrt** [comment]
I assume that's watchers, not stargazers.  I didn't get any emails

**Comment by Pholey** [comment]
closed as https://github.com/dogescript/dogescript/pull/117 has been merged
