### ISSUE TITLE
add keyword for the dot operator to `like`

### ISSUE THREAD

**Issue by synthet1c** [dogescript/dogescript#128]
Hey, can you consider adding the keyword `like` for the object dot operator.

### dogescript
```dogescript
such color much pretty 
dogument like body like style is pretty
wow pretty

plz color '#bada55'
```

### javascript
```javascript
function color(pretty) {
  document['body']['style'] = pretty // || document.body.style = pretty
  return pretty
}

color('#bada55')
```

**Comment by AnEmortalKid** [comment]
When we looked at #35  and consolidated this particular thing in #114 , we considered:

`giv` or `from`:

```
document giv body giv style is pretty
```

We currently don't use the `like` keyword, but it was suggested that we try to fix the ambiguity between `==` and `===`.

I see the definition being:
`is -> ===`
`aint -> !==`
`like -> ==`

Based on my understanding of `==` and `===`

**Comment by AnEmortalKid** [comment]
@vpzomtrrfrt / @Pholey  thoughts?

**Comment by vpzomtrrfrt** [comment]
I agree that `like` would make more sense for comparisons than property access.  We could use such an operator, but that's addressed in those other issues

**Comment by AnEmortalKid** [comment]
@synthet1c , sorry this took so long. 192 is ready to be reviewed :)
