### ISSUE TITLE
more natural dogespeak possible?

### ISSUE THREAD

**Issue by 00dani** [dogescript/dogescript#15]
I tried writing a little Mocha spec in dogescript 1.0.0:

```
plz describe with 'suchFunction' much
  plz it with 'does thing' much done
    plz suchFunction with done
  wow
wow
```

Now lambdas are in, it's possible to write reasonably nice specs, but I think it'd look _much_ code if it were possible to move the `with` keyword around. Take a look at this:

```
plz describe 'suchFunction' with much
  plz it 'does thing' with much done
    plz suchFunction with done
  wow
wow
```

Would permitting the above syntax introduce too much ambiguity in the parser?

**Comment by Pholey** [comment]
Moving to https://github.com/dogescript/dogescript/issues/115
