### ISSUE TITLE
Escaping quotes doesn't work correctly

### ISSUE THREAD

**Issue by vpzomtrrfrt** [dogescript/dogescript#177]
Attempting to escape a single quote within a string seems to add extra characters after it.
- `very a is '\''` is turned into `var a = '\' ';`
- `plz foo with '\''` is turned into `foo('\', ');`

**Comment by AnEmortalKid** [comment]
Well...... im a bit puzzled at what's happening here:

```js
$ node
> var line = "plz foo with '\''";
undefined
> line
'plz foo with \'\'\''
> line.match(/'[^']+'|\S+/g)
[ 'plz', 'foo', 'with', '\'\'\'' ]
> '\''.match(/'[^']+'|\S+/g)
[ '\'' ]
```

So the 'tokenizer' is identifying 4 chunks, at least through node. When I debug through it it somehow matches 5:

![image](https://user-images.githubusercontent.com/3474369/53282197-14c9bc80-36fa-11e9-8574-ffa70a901583.png)

**Comment by AnEmortalKid** [comment]
I have something partial here (before trying to swap out the tokenizer, I wanted to test it out)

https://github.com/AnEmortalKid/dogescript/blob/tokenizer/test/tokenizer.test.js#L19

Surprisingly, that last test doesn't fail.

**Comment by AnEmortalKid** [comment]
I think the problem might be related to something escaping the input:
```
$ cat escaped.djs
very a is '\''
$ dogescript escaped.djs
var a = '\' '
;
```

**Comment by AnEmortalKid** [comment]
@vpzomtrrfrt I think i might have a fix for this:
```
DOGE> very a is '\''
undefined
DOGE> a
'\''
```

However, some of the tests sort of expect extra lines......

```
# multi-props
not ok 202 should be equal
  ---
    operator: equal
    expected: |-
      'function foo() {\n    // 1\n}\n\nfunction bar(arg) {\n    // 2\n}\n\nmodule.exports.boo = foo\nmodule.exports.far = bar'
    actual: |-
      'function foo() {\n    // 1\n}\n\nfunction bar(arg) {\n    // 2\n}\nmodule.exports.boo = foo\nmodule.exports.far = bar'
```
