### ISSUE TITLE
Remove isDogescriptSource

### ISSUE THREAD

**Issue by AnEmortalKid** [dogescript/dogescript#182]
The parser gets around some of the token identification issues found in https://github.com/dogescript/dogescript/issues/177 in addition to others. 

Right now, when we parse:
```
[1, 2, 3]
```

We actually create these as tokens:
```
[ "[1," , "2," , "3]" ]
```

`joinTokens()` fixes this back up into the correct array declaration. However, if we were to get rid of isDogescriptSource today, we'd get something like:

```
"[1,"
"2,"
"3]"
```

I think fixing the way we identify tokens should take:
```
[1, 2, 3]
``` 

And return a single token:
```
[ "[1, 2, 3]" ]
```

The same might apply to json strings, since we have a bunch of "fixing" code where we will fix up arrays, see:
```
  // the token regex will split {a: b} into {a:, b, } which will cause us to append ', }'
  if (statement.includes(', ]'))
  {
    statement += statement.replace(/, ]/g, ']');
  }
  if (statement.includes(', }'))
  {
    statement = statement.replace(/, }/g, '}');
  }
```

**Comment by AnEmortalKid** [comment]
This might even let us identify these as tokens (each a single value):
```
'single quotes!'

"multi quote"

`omg
multiline?
weow
`
```

**Comment by AnEmortalKid** [comment]
@vpzomtrrfrt would the lexing code you have in the prototype of 3.x sort of return these as strings (not as the json token representation with the AST type) ?

**Comment by vpzomtrrfrt** [comment]
I'm not sure I understand the question?

**Comment by AnEmortalKid** [comment]
Ah, i was wondering if you had better "token" recognition in your version of the parser that is not a regex!

**Comment by vpzomtrrfrt** [comment]
Well, my current implementation doesn't really have "tokens", but I definitely don't have any regexes
