### ISSUE TITLE
Object literals don't work in reassignment

### ISSUE THREAD

**Issue by vpzomtrrfrt** [dogescript/dogescript#183]
This is the object syntax, right?
```
very a is obj
    foo: 5
wow
```
This works, but if I try to assign to an existing variable, i.e. without `very`, the construct isn't parsed:
```
DOGE> a is obj
a = obj;
ReferenceError: obj is not defined
```

**Comment by AnEmortalKid** [comment]
Yep. I'm hoping with the recursive bit that we can handle this case now! There's some ambiguity we'll have to solve with `is` in the conditional flow case vs the non-conditional.
