### ISSUE TITLE
Object declaration with curly braces no longer works

### ISSUE THREAD

**Issue by vpzomtrrfrt** [dogescript/dogescript#187]
To be fair, a lot of the doge3 source is workarounds for the way 2.3 handles things, but ideally we wouldn't be breaking anything in 2.4.

This snippet (line 267):
```
result is {
    'type': 'call',
    'function': callee,
    'args': args
}
```
Formerly compiled this way:
```
result = {
                        'type': 'call',
                        'function': callee,
                        'args': args
                }
```
But now results in this:
```
result = {
;
'type' : 'call' ,
'function' : callee,
'args' : args
}
```
There's an extra semicolon after the opening brace now, which throws a SyntaxError when run

**Comment by AnEmortalKid** [comment]
Ah, probably introduced by the most recent commit. I can check tonight, but I’m guessing an update to shouldCloseStatement would fix this. I don’t think we had any tests for multiline json declaration without the obj keyword so I’ll grab this scnario for it!
