### ISSUE TITLE
Spec improvements

### ISSUE THREAD

**Issue by KoryNunn** [dogescript/dogescript#19]
I'm currently toying with writing a JS to doge converter, and there are some parts of the spec that have fallen down a little.

Obviously everyone wants dogescript to be taken seriously, we all want much enterprise and very develop, so I think some parts of the spec should be changed.

semicolons: converting from JS to doge results in a whole lot of 'next's'.

parentheses: How should the be handled? leave as is, or maybe a more readable string similar to 'many'.

Also it would be nice if dogescript preferred arbitrary spacing between statements, eg:

```
such doge much woof
                                         console.loge with woof
              wow
```

**Comment by AnEmortalKid** [comment]
true doge will be deprecated. probably with proper precedence parenthesis will be handled. since truedoge is deprecated in #114 . closing this.
