### ISSUE TITLE
When will http://dogescript.io/live/ be fixed?

### ISSUE THREAD

**Issue by Purpzie** [dogescript/dogescript#212]
It seems to use an older version of dogescript at the moment. Most of the newer keywords don't seem to work or be acknowledged at all.

**Comment by AnEmortalKid** [comment]
I'm not sure, right out the bat where the dogescript version is defined / comes from.

 If it's a simple import from a CDN, it might have to wait until 2.4.0 is released OR we can release a 2.4.0-rc1 (release candidate). I've never published something on npm b4, but I could probably get @Pholey to do it. 

If it's something we can define in the assets (https://github.com/dogescript/dogescript.github.io/blob/dc4f094d4d608569369b17ae4e3d36a36e3f8581/assets/js/bundle.js#L2 ) haven't checked yet, it might be quicker.

I'll dig through this!

**Comment by AnEmortalKid** [comment]
@vpzomtrrfrt when you revived this, do you recall finding where the `dogescript` module gets referenced?

**Comment by AnEmortalKid** [comment]
Looks like it's loaded within the assets/bundle stuff:
https://github.com/dogescript/dogescript.github.io/commit/5cef11e6f7349fc0c57c0b2eac21b1bc46a9c628#diff-cd558f86921318569c331cbce0ade902R46

Might not be 2 hard!

**Comment by AnEmortalKid** [comment]
@Purpzie i've added a PR to the pages repo. if you'd like to spot check me, feel free to do so. Otherwise i'll probably merge this in about 2 days!

**Comment by Purpzie** [comment]
Thank you so much! 😃

**Comment by AnEmortalKid** [comment]
![image](https://user-images.githubusercontent.com/3474369/57184979-6aa0aa80-6e89-11e9-8253-5c6e881a6fbf.png)

its up now!
