### ISSUE TITLE
wow. such ideas

### ISSUE THREAD

**Issue by es128** [dogescript/dogescript#35]
much punctuation
so yuck
wow

"from" for object properties
`prop from obj` -> `obj.prop`

"bone from" for class properties/methods
`method bone from klass` -> `klass.prototype.method`

"number" or "levl" (or something like that)  for array and object lookups
`ary number 1` -> `ary[0] // -1 from ints, doge count from 1`
`ary levl i` -> `ary[i]`
`obj levl prop` -> `obj[prop]`

"pack" for array definition
`ary is pack` -> `ary = []`
`pack 1 two 'three'` -> `[1, two, 'three']`

"pares" for object definition
`obj is pares` -> `obj = {}`
`pares one 1 two 2 three 3` -> `{'one': 1, 'two': 2, 'three': 3}`

"the" allowed anywhere and parsed out
`the name from cat from the alley is 'dogefood'` -> `alley.cat.name = 'dogefood'`

I'd be happy to implement any/all of these. Just let me know which ones you like and if you think of any better terms/spellings.

**Comment by dopesaur** [comment]
I also think that for there's should be implemented two identical comparison operators:
`totally` – ===
`noway` – !==

@es128,
> the name from cat from the alley is 'dogefood' -> alley.cat.name = 'dogefood'
Yuck, that's looks like AppleScript:
> get the document of front window

**Comment by AnEmortalKid** [comment]
closing since ideas  have been attached in #114
