### ISSUE TITLE
is conflict

### ISSUE THREAD

**Issue by es128** [dogescript/dogescript#45]
`is` is currently being used in dogescript for both assignment and as a comparator. It works, but aside from the potential for confusion and bugs, another side effect of this is the way it's implemented causes all the operators to be very restricted in their usage.

For example, `index more 1`, which should compile to `index += 1`, doesn't work.

I suggest the assignment form of `is` be renamed to `as` (which is already somewhat implemented), and the operators be made universally available. This will facilitate the addition of `also` for `,` and a global removal of `the`.

An alternative would be renaming the comparator `is` to `same`.

**Comment by AnEmortalKid** [comment]
Tracking in #114
