### ISSUE TITLE
DSON + Dogescript

### ISSUE THREAD

**Issue by remixz** [dogescript/dogescript#68]
I've just started writing a DSON (http://dogeon.org) parser in Dogescript, because I'm a little bit insane. https://github.com/remixz/DSON.djs. 

I like the idea of having better object support in Dogescript, though the current DSON spec interferes a lot of the Dogescript keywords, so it'd have to be modified a bit. I'm wondering if anyone had thoughts on whether or not DSON should be part of Dogescript?

**Comment by Pholey** [comment]
moved to https://github.com/dogescript/dogescript/issues/115
