### ISSUE TITLE
functions as variable for other functions

### ISSUE THREAD

**Issue by marionauta** [dogescript/dogescript#71]
such problem

if I have a function with a return value:

```
such test much number
    very result is number * number
wow result
```

I can't call it direcly like

```
plz console.loge with plz test with 5
```

nor

```
plz console.loge with (plz test with 5)
```

**Comment by AnEmortalKid** [comment]
Yeah, I've found this problem too. I think with a proper parser, we could support this. There's a dogescript-3 project out there with pegjs support, so i'm going to check that out and see if it can do calls like that.

**Comment by AnEmortalKid** [comment]
So, I grabbed and modified some of the pegjs code that idunnowhy9000 [wrote](https://raw.githubusercontent.com/idunnowhy9000/dogescript/master/src/dogescript/doge.pegjs)

And tried it on the pegjs online ui: https://pegjs.org/online

Given:
`plz doge with plz cat`

The parser produced:
```json
{
   "type": "Program",
   "body": [
      {
         "type": "ExpressionStatement",
         "expression": {
            "type": "CallExpression",
            "callee": {
               "type": "Identifier",
               "name": "doge"
            },
            "arguments": [
               {
                  "type": "CallExpression",
                  "callee": {
                     "type": "Identifier",
                     "name": "cat"
                  },
                  "arguments": []
               }
            ]
         }
      }
   ]
}
```

So this would be solveable.

**Comment by AnEmortalKid** [comment]
We just need proper presedence to solve it.

**Comment by Pholey** [comment]
Moving to 3.0 for proper precedence https://github.com/dogescript/dogescript/issues/115
