### ISSUE TITLE
Future of Dogescript

### ISSUE THREAD

**Issue by remixz** [dogescript/dogescript#72]
Hi all! I just wanted to talk about a potential future of Dogescript.

Dogescript has matured a lot since it started, and just recently has seen a surge in activity thanks to awesome community materials being made, and the creation of DSON. There's been some exciting work started as well by @Pholey, who is working on rewriting Dogescript to use a lexer written in... Dogescript! :smile: It's early on still, but it could be really cool. I've been thinking about the future of Dogescript, and here is my proposal:
## Dogescript 2.4.0

I'd like to do a 2.4.0 release, which would still be written in the current crazy JS that it is. This release would be an opportunity to create a nice stable base for Dogescript 3.0.0 (see next section). I'd like to add some features that would be helpful for @Pholey in writing a parser with Dogescript. Maybe the current language is good enough, but I'm sure there could be something. As well, I'd like to fix some of the bugs and edge cases, just so there can be less hacks. If there any features you'd like to see in Dogescript, please comment them here. When 2.4.0 is released, any feature development for Dogescript will be frozen.
## Dogescript 3.0.0

3.0! This release could be characterized by two things: a parser rewrite, and native DSON support. I say could, as either of these may be too much of a long shot. I think they could happen though. (@Pholey not to put any pressure on you!) For a parser rewrite, Dogescript 3.0.0 would be compiled with the stabilized 2.4.0. For DSON support, it would likely integrate [DSON.djs](https://github.com/remixz/DSON.djs), and import it as a global variable, similar to JSON. This is all pretty loose though, so any feedback is welcome.
## Community

The Dogescript community is, while small, still pretty awesome. One thing I'd like to do is add some more contributors to this repo. If you've written something cool in Dogescript, written documentation, etc., please leave a comment here, or get in touch with me (mail@bruggie.com). I wouldn't really be asking you to do anything specifically, but it would be just helping out with the repo. (merging PRs that you think are good, developing features, collecting resources, creating new resources, etc) I've done my best to do this myself, but I'm not always around to do so. If there's more of us, maybe we can catch even more cool stuff!

As well, I'm wondering if there should be more of a hub for Dogescript. The current site is very... bland, so it might be nice if there was a proper website. Maybe a blog? (GH-36) This does make Dogescript seem bigger than it actually is, but from what I can tell, there's actually a decent amount of Dogescript projects, just no place to collect them.

As always, if you have any feedback, questions, or whatever, leave them here!

**Comment by Pholey** [comment]
Moved to https://github.com/dogescript/dogescript/issues/115 and https://github.com/dogescript/dogescript/issues/114
