### ISSUE TITLE
Need a feature for commonJS module.exports

### ISSUE THREAD

**Issue by Bartvds** [dogescript/dogescript#73]
As companion for `so [module]`

Something good to map to either `module.exports = foo;` or `exports.xyz = bar;`

**Comment by AnEmortalKid** [comment]
`bark [function_name]` could even look like `bark funky is such parse much dogescript‘ => ’module.exports = function parse(dogescript)‘

**Comment by AnEmortalKid** [comment]
closing since tracking on #114
