### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by Bartvds** [dogescript/dogescript#78]
Since the language is evolving again it could be time to add a test suite where we can add cases to make sure the compiler follows the spec and we don't create regressions.

If you agree this is a good idea then I offer to set something up using for example grunt, mocha and chai.

It'd be something dynamic to make it is easy to add new cases (eg: file based) (been there, done that).

And of course we then link it to Travis-CI (free for OSS) so Github can test on Pull Requests and Merges.

**Comment by AnEmortalKid** [comment]
closing as tests exists and were added.
