### ISSUE TITLE
Anonymous function support

### ISSUE THREAD

**Issue by remixz** [dogescript/dogescript#87]

**Comment by Pholey** [comment]
to retouch on this, i was thinking `much` by itself seems good and consistent:

```
shh Functions with a name and no parameters
such burp
  console.loge "Burp!" 

shh Functions with a name and  parameters
such eat much weight
  wow weight more 1

shh Functions without a name, and parameters
much number
   wow number more 1
```

this may involve finding a new word for `for` though

**Comment by AnEmortalKid** [comment]
partially supported here #104 , with wacky syntax `such much`. Ideally, we'd find a better word for `for` and we could break passivity and have `much a b` be the declaration for anonymous functions.

**Comment by AnEmortalKid** [comment]
closing since we can argue about the new for word here: #105

**Comment by AnEmortalKid** [comment]
Closing since tracked in #114
