### ISSUE TITLE
Check for operators in whitespace sensitive parameters

### ISSUE THREAD

**Issue by Pholey** [dogescript/dogescript#88]
For example, when one involks the function x like so:

`plz x with "h" + "ello"`

it compiles down to something like:

``` javascript
x("h", +, "ello");
```

**Comment by Pholey** [comment]
With a proper parser and precedence, We could avoid the syntax change all together... Sadly ican't think of a graceful fix in the mean time...

**Comment by AnEmortalKid** [comment]
Introducing `also` would make it non passive..... so we should just defer this to a 3.0 (probably proper parsing)

**Comment by Pholey** [comment]
`also|and` sounds like a good solution to me as well. Lets get it into 3.0

**Comment by AnEmortalKid** [comment]
I like also (since and is already an operator and we don't want namespace conflicts again: `much loop` `much args` !

**Comment by Pholey** [comment]
Closing as this has been moved to https://github.com/dogescript/dogescript/issues/115
