### ISSUE TITLE
Added script tag capability

### ISSUE THREAD

**Issue by Bartvds** [dogescript/dogescript#91]
I hacked a simple implementation that can parse script tags with 'text/dogescript' type... because.. I don't know.. :smile:

Can be both inline and external script:

```
<script type="text/dogescript" src="doge.djs">
```

```
<script type="text/dogescript">
plz console.loge with 'wow script'
</script>
```

I pushed it here: https://github.com/dogescript/dogescript/tree/inline

But I'm not sure how to finalise this, some issues:
1. For now I put it in `index.js` so it can be browserified, is that right?
2. Currently we don't have pre-build browserified dists in the repo yet (like `dist/dogescript.js` and  `dist/dogescript.min.js`) 
3. Browserify will diligently include jsbeautify but I'm not sure if it is needed (not that big a deal really).

**Comment by Pholey** [comment]
Closing as this has been merged
