### ISSUE TITLE
Add browserified dist files

### ISSUE THREAD

**Issue by Bartvds** [dogescript/dogescript#92]
Pre-bundle browser versions, as per #91 

```
/dist/dogescript.js
/dist/dogescript.min.js
```

Should probably be a npm 'build' script:

```
npm run build
```

Once both this and #91 lands we can add dogescript to bower and http://cdnjs.com/

**Comment by Pholey** [comment]
Closing since bower now officially suggests moving to (yarn)[https://yarnpkg.com/en/] and the build script has been merged.
