### ISSUE TITLE
dogescript should be written in dogescript

### ISSUE THREAD

**Issue by volter9** [dogescript/dogescript#96]
Hello there, dogsscript is such very wow. Why wouldn't you rewrite dogescript in dogescript like coffeescript is written in [coffeescript](https://github.com/jashkenas/coffeescript)?

Just an idea, and thank you for dogescript. :+1:

**Comment by Pholey** [comment]
@Volter9 Initially this was the goal for dogescript 3.0, (I even [started on porting a lexer](https://github.com/dogescript/dogescript-lexer/blob/master/lexer.djs) for the language) but ultimately decided that the dogescript had too many crippling parse bugs for it to be viable... (You can find some of them in the comments)

The goal is currently for 3.0 is to [rewrite the current dogescript compiler](https://github.com/dogescript/dogescript/tree/such-rewrite) in ES6, then port that over to dogescript afterwards (ending in full ES6 support hopefully!)

So all in all, it's planned! Just need to complete a few steps first!

**Comment by Volter9** [comment]
You seem to have problem with anonymous functions, `new` stuff, and throw stuff.

Maybe, in dogescript 3.0, anonymous fuctionz, "classes", exceptions should be added?

Oh, and also, can I port dogescript to PHP? :smiley:

**Comment by remixz** [comment]
@Pholey i'm super excited to see the fruits of your labour with the es6 rewrite branch! btw, what's your npm username? i wanna add you to `dogescript` on npm, so you can publish stuff eventually.

@Volter9 go for it! dogescript all the languages!

**Comment by idunnowhy9000** [comment]
hey @remixz, @Pholey, I already rewrote [dogescript in pegjs](https://github.com/idunnowhy9000/dogescript)

**Comment by dopesaur** [comment]
What a coincidince, I ported (with few modifications, and added few features) [dogescript to PHP](https://github.com/dopesaur/dogescript-php). :smiley:

I didn't wrote how to use it, yet.

**Comment by Pholey** [comment]
@remixz Awesome! My username on npm is the same as it is here, `pholey`. 

@idunnowhy9000, @dopesaur  thats awesome! 

@dogescript/owners On another note, i was wondering if we could start a room for discussion, maybe on IRC or something? I have various syntax changes i'd like to discuss, as well as a need for feedback before i implement a number of things. As much as i love github, i feel it would be more productive via instant means of communication.

**Comment by AnEmortalKid** [comment]
@idunnowhy9000 did you end up fixing anonymous functions in your pegjs version?

**Comment by Pholey** [comment]
closing and Moving to another ticket https://github.com/dogescript/dogescript/issues/115
